inherit_from: ~/.config/rubocop/config.yml

AllCops:
  TargetRubyVersion: 3.1

# setting to 6 to match RubyMine autoformat
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  IndentationWidth: 6

RSpec/ExampleWording:
  Enabled: false
